[package]
name = "privateoracle"
type = "contract"
authors = ["wonderland"]
compiler_version = "0.17.0"

[dependencies]
aztec = { git="https://github.com/AztecProtocol/aztec-packages/", tag="aztec-packages-v0.12.0", directory="yarn-project/aztec-nr/aztec" }